### ISSUE TITLE
Add 'constant' keyword to the variables that do not change their values

### ISSUE THREAD

**Issue by pauliax** [vrexlab/dyverse-bounty#2]
contract KydyMinting
    
uint256 public promoCreationLimit = 888;
uint256 public gen0CreationLimit = 8888;

This is not a bug. Consider adding keyword "constant" to the variables that do not change their values. Reading from a const variable doesn't cost any gas and it also improves the readability of the code.

**Comment by ouoabcde** [comment]
I'll consider it, too. Thanks for your participation. I'll tag you on it's PR.
