### ISSUE TITLE
Anyone can cancel the auction

### ISSUE THREAD

**Issue by pauliax** [vrexlab/dyverse-bounty#5]
contract ClockAuction
function cancelAuction(uint256 _tokenId, address _seller)

This function has public accessibility and no restrictions (can be called by anyone). It does not check who is the tx initiator. It only checks that the auction is live and that parameter _seller is the real seller:
`address seller = auction.seller;`

Imagine a situation: player A puts his token on sale, then player B calls cancelAuction passing address of player A as a _seller parameter. The auction will be cancelled and the token returned to the player A even though player A had no intentions cancelling this auction. He has to start the auction again and spend gas, but player B can cancel it once again.

Fix:
remove _seller parameter and change the check to this:
`require(msg.sender == seller);`

**Comment by ouoabcde** [comment]
Yeah. This is a bug. I'll try to fix this. Thanks a lot @pauliax 👍

**Comment by pauliax** [comment]
Probably my suggested fix is not correct. As I looked forward, this function is probably intended to be called from contract KydyAuction which performs the authorization checks.

**Comment by ouoabcde** [comment]
Yeah you're right. We intended to use `cancelAuction` function(which at ClockAuction.sol) only from `cancelSaleAuction` function from KydyAuction.sol. So I'm gonna fix `cancelAuction` function would only called from KydyAuction.sol. Plus, I trying to add more authorization checks at `cancelSaleAuction`.
